TARGET_PATH :=$(call my-dir)
TOP_PATH := $(TARGET_PATH)

include $(ENV_CLEAR)
TARGET_SRC := source/tools/udev_handler.c

TARGET_CPPFLAGS += -DHAS_BDROID_BUILDCFG -DLINUX_NATIVE -DANDROID_USE_LOGCAT=FALSE -DSBC_FOR_EMBEDDED_LINUX
TARGET_LDFLAGS +=
TARGET_MODULE := udev_handler
include $(BUILD_BIN)

